parameters:
  - name: azureSubscriptionEndpoint
  - name: azureContainerRegistry
  - name: dockerComposeFile
  - name: projectName
  - name: qualifyImageNames

jobs:
  - job: 'PushServices'
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerCompose@0
        displayName: Push services
        inputs:
          action: Push services
          containerregistrytype: Azure Container Registry
          azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
          azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
          dockerComposeFile: ${{ parameters.dockerComposeFile }}
          projectName: ${{ parameters.projectName }}
          qualifyImageNames: ${{ parameters.qualifyImageNames }}