version : '3'
services:
  mysql:
    image: uzubwttacr.azurecr.io/mysql
    container_name: mysql-container
    build: 
      context: .
      dockerfile: ./api/db/Dockerfile
    volumes:
       - "./api/db/data:/var/lib/mysql"
       - "./api/db/scripts:/docker-entrypoint-initdb.d"
    ports:
       - 3306:3306

  api:
    image: uzubwttacr.azurecr.io/api
    container_name: api-container
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
       - "./api:/home/node/app"
    ports:
       - 9001:9001
    restart: "always"
    depends_on:
      - "mysql"

  website:
    image: uzubwttacr.azurecr.io/website
    container_name: website-container
    build: 
      context: .
      dockerfile: ./website/Dockerfile
    volumes:
       - "./website:/var/www/html"
    ports:
       - 8888:80
    restart: "always"
    depends_on:
      - "api"

volumes:
    hi:
      driver: azure_file
      driver_opts:
          share_name: <name of share>
          storage_account_name: <name of storage account>