version : '3'
services:
  mysql:
    image: <acrName>.azurecr.io/mysql
    container_name: mysql-container
    build: 
      context: ./db
      dockerfile: Dockerfile
    volumes:
       - "./db/data:/var/lib/mysql"
       - "./db/scripts:/docker-entrypoint-initdb.d"
    ports:
       - 3306:3306

  api:
    image: <acrName>.azurecr.io/api
    container_name: api-container
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
       - "./api:/home/node/app"
    ports:
       - 9001:9001
    restart: "always"
    depends_on:
      - "mysql"

  website:
    image: <acrName>.azurecr.io/website
    container_name: website-container
    build: 
      context: ./website
      dockerfile: Dockerfile
    volumes:
       - "./website:/var/www/html"
    ports:
       - 8888:80
    restart: "always"
    depends_on:
      - "api"