version : '3'
services:
  mysql:
    container_name: mysql-container
    build: 
      context: .
      dockerfile: ./api/db/Dockerfile
    volumes:
       - "./api/db/data:/var/lib/mysql"
       - "./api/db/scripts:/docker-entrypoint-initdb.d"
    ports:
       - 3306:3306

  api:
    container_name: api-container
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
       - "./api:/home/node/app"
    ports:
       - 9001:9001
    restart: "always"
    depends_on:
      - "mysql"

  website:
    container_name: website-container
    build: 
      context: .
      dockerfile: ./website/Dockerfile
    volumes:
       - "./website:/var/www/html"
    ports:
       - 8888:80
    restart: "always"
    depends_on:
      - "api"