name: Build $(build_counter)

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - terraform-live
    - pipelines/azure-pipelines.yaml
    - pipelines/templates

variables:
  build_counter: $[counter('build-counter-$(RELEASE_NAME)', 1)]
  project_name: "demo-containers"
  service_connection_name: "SC-AzureDevOps" 
  tfstate_storage_account_resource_group_name: "demo-containers-rg"
  tfstate_storage_account_name: "stacdev"
  tf_version: 1.2.6
  tf_script_path: "$(System.DefaultWorkingDirectory)/terraform-live"
  resource_group_name: "demo-containers-dev"
  qualify_image_names: true
  #tf_modules_path: '$(System.DefaultWorkingDirectory)/terraform-modules'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: QualityCheckStage
    displayName: Quality Check Stage
    jobs:
      - job: TFSecJobMain
        displayName: TFSec Scan terraform-acr
        steps:
          - template: ./templates/steps/tfsec.yaml
            parameters:
              artifact_name: 'terraform-acr'
              working_path: '${{ variables.tf_script_path }}/terraform-acr'

  - stage: dev
    jobs:
      - job: plan
        displayName: Plan Dev Environment
        steps:
        - template: ./templates/steps/azure-setup.yaml
          parameters:
            tags: '"UseCase=Terraform" "Stage=dev"'
            resource_group_name: ${{ variables.tfstate_storage_account_resource_group_name }}
            storage_account_name: ${{ variables.tfstate_storage_account_name }}
            resource_group_location: "westus"
            service_connection_name: ${{ variables.service_connection_name }}

        - template: ./templates/steps/terraform-plan.yaml
          parameters: 
            stage: dev
            tfstate_storage_account_resource_group_name: ${{ variables.tfstate_storage_account_resource_group_name }}
            service_connection_name: ${{ variables.service_connection_name }}
            tfstate_storage_account_name: ${{ variables.tfstate_storage_account_name }}
            tf_version: ${{ variables.tf_version }}
            project_name: ${{ variables.project_name }}
            working_path: '${{ variables.tf_script_path }}/terraform-acr'
            var_file: '${{ variables.tf_script_path }}/dev.tfvars'

      - job: apply
        dependsOn: plan
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        displayName: Terraform Apply ACR
        steps:
          - template: ./templates/steps/terraform-apply.yaml
            parameters:
              stage: dev
              tfstate_storage_account_resource_group_name: ${{ variables.tfstate_storage_account_resource_group_name }}
              service_connection_name: ${{ variables.service_connection_name }}
              tfstate_storage_account_name: ${{ variables.tfstate_storage_account_name }}
              tf_version: ${{ variables.tf_version }}
              project_name: ${{ variables.project_name }}
              working_path: '${{ variables.tf_script_path }}/terraform-acr'

          - task: Bash@3
            displayName: 'Terraform Output'
            inputs:
              targetType: 'inline'
              script: |
                terraform output -json > ./output.json
              workingDirectory: '${{ variables.tf_script_path }}/terraform-acr'

          - bash: |
              get_acr_name=$(jq -r .acr_name.value.output ${{ variables.tf_script_path }}/terraform-acr/output.json)
              echo "##vso[task.setvariable variable=acr_name;isoutput=true]${acr_name}"
            name: applyOutput

      - job: mysqlbuildpush
        dependsOn: apply
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        variables:
          acr_name: $[ dependencies.apply.outputs['applyOutput.acr_name'] ] 
        displayName: Build and Push Mysql
        steps:
        - task: DockerCompose@0
          displayName: Build services
          inputs:
            action: Build services
            azureSubscriptionEndpoint: ${{ variables.service_connection_name }}
            azureContainerRegistry: '$(acr_name).azurecr.io'
            dockerComposeFile: db/docker-compose.yml
            projectName: mysql-$(System.StageName)
            qualifyImageNames: ${{ variables.qualify_image_names }}
            
        - task: DockerCompose@0
          displayName: Push services
          inputs:
            action: Push services
            containerregistrytype: Azure Container Registry
            azureSubscriptionEndpoint: ${{ variables.service_connection_name }}
            azureContainerRegistry: '$(acr_name).azurecr.io'
            dockerComposeFile: db/docker-compose.yml
            projectName: mysql-$(System.StageName)
            qualifyImageNames: ${{ variables.qualify_image_names }}
        # - bash: |
        #     echo $(myVarFromJobA)
          # - task: AzureCLI@2
          #   displayName: 'Get ACR Name'
          #   inputs:
          #     azureSubscription: ${{ variables.service_connection_name }}
          #     scriptType: 'bash'
          #     scriptLocation: inlineScript  
          #     inlineScript: |
          #       echo $(myVarFromJobA)
