trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE
    - api
    - website
    include:
    - db
    - pipelines/database/azure-pipelines.yml

parameters:
  - name: azureContainerRegistry
    default: wttohsfacr.azurecr.io
  - name: azureSubscriptionEndpoint
    default: AzureDevOps

pool:
  vmImage: ubuntu-latest

stages:
  - stage: main
    jobs:
      - template: ../templates/docker-compose/build-push.yml
        parameters:        
          azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
          azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
          dockerComposeFile: db/docker-compose.yml
          projectName: mysql
          qualifyImageNames: true
          jobName: MySqlDockerCompose