version : '3'
services:
  website:
    image: website
    container_name: website-container
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_ADDRESS=${BACKEND_ADDRESS}
    volumes:
       - "./website:/var/www/html"
    ports:
       - 8888:80
    restart: "always"
    environment:
      BACKEND_ADDRESS: ${BACKEND_ADDRESS}