version : '3'
services:
  api:
    image: api
    container_name: api-container
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - MYSQL_HOST=${MYSQL_HOST}
    volumes:
       - "./api:/home/node/app"
    ports:
       - 9001:9001
    restart: "always"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}